/**
 * Presentation Exchange API
 * Presentation Exchange API
 *
 * The version of the OpenAPI document: 2.1.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AcpPolicy } from "./AcpPolicy";


/**
 * Input Descriptor is used by a Verifier to describe the information required of a Holder before an interaction can proceed.
 */
export interface AuthenticatedAcpPolicy {
    '@context': [string]
    type?: [string];
    definedACPContext: AcpPolicy,
    proof: object
}

