/**
 * Presentation Exchange API
 * Presentation Exchange API
 *
 * The version of the OpenAPI document: 2.1.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubmissionRequirement } from './submissionRequirement';
import { Format } from './format';
import { InputDescriptorV1 } from './inputDescriptorV1';
import { AcpPolicy } from './AcpPolicy';
import { AuthenticatedAcpPolicy } from './AuthenticatedAcpPolicy';


/**
 * Version 1 of Presentation Definitions are objects that articulate what proofs a Verifier requires.
 */
export interface PresentationDefinitionV1 {
    /**
     * A UUID or some other unique ID to identify this Presentation Definition
     */
    id: string;

    /**
     * The Policy related to the Presentation Definition
     */
    requestACP?: AcpPolicy | AuthenticatedAcpPolicy;
    /**
     * A name property is a human-friendly string intended to constitute a distinctive designation of the Presentation Definition.
     */
    name?: string;
    /**
     * It describes the purpose for which the Presentation Definition\'s inputs are being requested.
     */
    purpose?: string;
    format?: Format;
    /**
     * List of requirements for described inputs in input descriptors.
     */
    submission_requirements?: Array<SubmissionRequirement>;
    /**
     * List of descriptions of the required inputs.
     */
    input_descriptors: Array<InputDescriptorV1>;
}

